Project.MVCUI/Controllers/ShoppingController.cs
using PagedList;
using Project.BLL.DesignPatterns.GenericRepository.BaseRep;
using Project.BLL.DesignPatterns.GenericRepository.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using Project.MVCUI.Models.ShoppingTools;
using Project.MVCUI.VMClasses;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Controllers
{
    public class ShoppingController : Controller
    {
        OrderRepository _oRep;
        ProductRepository _pRep;
        CategoryRepository _cRep;
        OrderDetailRepository _odRep;

        public ShoppingController()
        {
            _cRep = new CategoryRepository();
            _odRep = new OrderDetailRepository();
            _pRep = new ProductRepository();
            _oRep = new OrderRepository();
            
        }
        public ActionResult ShoppingList(int? page,int? categoryID) //nullable int vermemizin sebebi aslında buradaki int'in kacıncı sayfada oldugumuzu temsil edecek olmasıdır...Ancak birisi direkt alısveriş sayfasına ulastıgında hangi sayfada oldugu verisi olamayacagından dolayı bu şekilde de (yani sayfa numarası gonderilmeden de) bu action'in calısabilmesini istiyoruz...
        {
            //string a = "Mehmet";

            //string b = a ?? "Cagrı"; //a null ise b'ye Cagrı degerini at...Ama a'nın degeri null degilse b'ye a'yı at...

            //    page ?? 1

            //page ?? ifadesi page null ise demektir

            PaginationVM pavm = new PaginationVM
            {
                Products = categoryID == null ? _pRep.GetActives().ToPagedList(page ?? 1, 9) : _pRep.Where(x=>x.CategoryID==categoryID).ToPagedList(page??1,9),
                Categories = _cRep.GetActives()
            };

            if (categoryID != null) TempData["catID"] = categoryID;


            return View(pavm);
        }

        public ActionResult AddToCart(int id)
        {
            Cart c = Session["scart"] == null ? new Cart() : Session["scart"] as Cart;
            Product eklenecekUrun = _pRep.Find(id);

            CartItem ci = new CartItem
            {
                ID = eklenecekUrun.ID,
                Name = eklenecekUrun.ProductName,
                Price = eklenecekUrun.UnitPrice,
                ImagePath = eklenecekUrun.ImagePath
            };

            c.SepeteEkle(ci);
            Session["scart"] = c;

            return RedirectToAction("ShoppingList");
        }

        public ActionResult CartPage()
        {
            if (Session["scart"] != null)
            {
                CartPageVM cpvm = new CartPageVM();
                Cart c = Session["scart"] as Cart;
                cpvm.Cart = c;
                return View(cpvm);
            }
            TempData["bos"] = "Sepetinizde ürün bulunmamaktadır";
            return RedirectToAction("ShoppingList");
        }

        public ActionResult DeleteFromCart(int id)
        {
            if (Session["scart"] != null)
            {
                Cart c = Session["scart"] as Cart;
                c.SepettenCikar(id);
                if(c.Sepetim.Count == 0)
                {
                    Session.Remove("scart");
                    TempData["sepetBos"] = "Sepetinizdeki tüm ürünler cıkartılmıstır";
                    return RedirectToAction("ShoppingList");
                }
                return RedirectToAction("CartPage");
            }

            return RedirectToAction("ShoppingList");
        }

        public ActionResult ConfirmOrder()
        {
            AppUser currentUser;
            if (Session["member"] != null)
            {
                currentUser = Session["member"] as AppUser;
            }
            else
            {
                TempData["anonim"] = "Kullanıcı üye degil";
            }

            return View();
        }


        //https://localhost:44329/api/Payment/ReceivePayment


        [HttpPost]
        public ActionResult ConfirmOrder(OrderVM ovm)
        {
            bool result;
            Cart sepet = Session["scart"] as Cart;
            ovm.Order.TotalPrice = ovm.PaymentDTO.ShoppingPrice = sepet.TotalPrice;

            #region APISection

            using(HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44329/api/");
                Task<HttpResponseMessage> postTask = client.PostAsJsonAsync("Payment/ReceivePayment", ovm.PaymentDTO);
                HttpResponseMessage sonuc;

                try
                {
                    sonuc = postTask.Result;
                }
                catch (Exception ex)
                {

                    TempData["baglantiRed"] = "Banka baglatıyı reddetti";
                    return RedirectToAction("ShoppinList");
                }
                if (sonuc.IsSuccessStatusCode) result = true;
                else result = false;

                if (result)
                {
                    if (Session["member"] != null)
                    {
                        AppUser kullanici = Session["member"] as AppUser;
                        ovm.Order.AppUserID = kullanici.ID;
                        ovm.Order.UserName = kullanici.UserName;
                    }
                    else
                    {
                        ovm.Order.AppUserID = null;
                        ovm.Order.UserName = TempData["anonim"].ToString();
                    }

                    _oRep.Add(ovm.Order); //OrderRepository bu noktada Order'i eklerken onun ID'sini olusturuyor...

                    foreach (CartItem item in sepet.Sepetim)
                    {
                        OrderDetail od = new OrderDetail();
                        od.OrderID = ovm.Order.ID;
                        od.ProductID = item.ID;
                        od.TotalPrice = item.SubTotal;
                        od.Quantity = item.Amount;
                        _odRep.Add(od);

                        //Stoktan da düsürelim
                        Product stokDus = _pRep.Find(item.ID);
                        stokDus.UnitsInStock -= item.Amount;
                        _pRep.Update(stokDus);
                    }

                    TempData["odeme"] = "Siparişiniz bize ulasmıstır...TEsekkür ederiz";
                    MailService.Send(ovm.Order.Email, body: $"Siparişiniz basrıyla alındı {ovm.Order.TotalPrice}");

                    Session.Remove("scart");

                    return RedirectToAction("ShoppingList");
                }
                else
                {
                    Task<string> s = sonuc.Content.ReadAsStringAsync();
                    TempData["sorun"] = s.Result;
                    return RedirectToAction("ShoppingList");
                }

            }




            #endregion
        }

    }
}

Project.MVCUI/Views/Shopping/CartPage.cshtml
@model CartPageVM


@{
    ViewBag.Title = "CartPage";
}

<div class="jumbotron">
    Odemeniz gereken toplam tutar => @Model.Cart.TotalPrice ...Siparişi oynaylamak icin lütfen @Html.ActionLink("tıklayınız","ConfirmOrder")
</div>

<div class="row product-list">
    @foreach (CartItem item in Model.Cart.Sepetim)
    {

        <div class="col-md-4">
            <section class="panel">
                <div class="pro-img-box">

                    @if (item.ImagePath == null || item.ImagePath == "3" || item.ImagePath.Contains("nightlife"))
                    {
                        <img src="/Pictures/330426628a1b02a7f2515bc99f2758e3.jpg" alt="Resim yok" width="100" height="300" title="@item.Name" />
                    }
                    else
                    {
                        <img src="@item.ImagePath" alt="Resim yok" width="200" height="200" title="@item.Name" />
                    }





                    <a href="@Url.Action("DeleteFromCart", new {id=item.ID})" class="adtocart">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>
                </div>

                <div class="panel-body text-center">
                    <h4>
                        <a href="#" class="pro-title">
                            @item.Name x @item.Amount 
                        </a>
                    </h4>
                    <p class="price">$@item.SubTotal</p>
                </div>
            </section>
        </div>

    }
</div>

Project.MVCUI/Views/Shopping/ConfirmOrder.cshtml
@model OrderVM
@{
    ViewBag.Title = "ConfirmOrder";
}

<div>
    @using (Html.BeginForm())
    {
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Gonderim Adresi

            </label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.Order.ShippedAddress, new { @class = "form-control" })
            </div>
            <br />

        </div> 
       


        <div style="padding-top:30px" class="form-group">
            <label class="col-sm-2 control-label">
                Kart Numarası

            </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentDTO.CardNumber, new { @class = "form-control" })
            </div>

            <br />
            <br />


        </div>

       

        <div class="form-group">
            <label class="col-sm-2 control-label">
                Kart Güvenlik Numarası

            </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentDTO.SecurityNumber, new { @class = "form-control" })
            </div>

            <br />
            <br />
        </div>


      

        <div class="form-group">
            <label class="col-sm-2 control-label">
                Gecerlilik süresi (Yıl)

            </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentDTO.CardExpiryYear, new { @class = "form-control" })
            </div>

            <br />
            <br />
        </div>

     

        <div class="form-group">
            <label class="col-sm-2 control-label">
                Gecerlilik süresi (Ay)

            </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentDTO.CardExpiryMonth, new { @class = "form-control" })
            </div>

            <br />
            <br />
        </div>

  


        <div class="form-group">
            <label class="col-sm-2 control-label">
                Kart Üzerindeki İsim

            </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentDTO.CardUserName, new { @class = "form-control" })
            </div>

            <br />
            <br />
        </div>

     

        <div class="form-group">
            <label class="col-sm-2 control-label">
                Email

            </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Order.Email, new { @class = "form-control" })
            </div>

            <br />
            <br />
        </div>

  


        <div class="form-group">
            <label class="col-sm-2 control-label">
                Onaylamak icin tıklayınız

            </label>
            <div class="col-sm-10">
                <button class="btn btn-primary">Onay</button>
            </div>

            <br />
        </div>

       
    }
</div>

Project.MVCUI/Views/Shopping/ShoppingList.cshtml
@model PaginationVM
@{
    ViewBag.Title = "ShoppingList";
}


@TempData["bos"]
@TempData["sepetBos"]
@TempData["baglantiRed"]

<div class="row">
    <div class="col-md-3">

        <section class="panel">
            <header class="panel-heading">
                Categories
            </header>
            <div class="panel-body">
                <ul class="nav prod-cat">

                    @foreach (Category item in Model.Categories)
                    {
                        <li style="padding-top:30px"> @Html.ActionLink(item.CategoryName, "ShoppingList", new { categoryID = item.ID }, new { @class = "btn btn-primary" }) </li>
                    }

                </ul>
            </div>
        </section>

    </div>
    <div class="col-md-9">
        <section class="panel">
            <div class="panel-body">
                <!--Linq icerisinde bir action URL'e yonlendirme yapmak isterseniz URL.Action Helper'i kullanabilirsiniz.-->

                <div class="pull-right">
                    <ul class="pagination pagination-sm pro-page-list">
                        @if (TempData["catID"] != null)
                        {
                            <li> @Html.PagedListPager(Model.Products, page => Url.Action("ShoppingList", new { page, categoryID = TempData["catID"] }))  </li>
                        }
                        else
                        {
                            <li>
                                @Html.PagedListPager(Model.Products, page => Url.Action("ShoppingList", new { page }))
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </section>

        <div class="row product-list">

            @foreach (Product item in Model.Products)
            {
                <div class="col-md-4">
                    <section class="panel">
                        <div class="pro-img-box">

                            @if (item.ImagePath == null || item.ImagePath == "3" || item.ImagePath.Contains("nightlife"))
                            {
                                <img src="/Pictures/330426628a1b02a7f2515bc99f2758e3.jpg" alt="Resim yok" width="100" height="300" title="@item.ProductName (@item.Category.CategoryName)" />
                            }
                            else
                            {
                                <img src="@item.ImagePath" alt="Resim yok" width="200" height="200" title="@item.ProductName" />
                            }


                            @*

                                Url.Action'in bize verdigi fayda, asagıdaki gibi belli durumlarda ActionLink kullanmak tasarımımıza uygun olmadıgı zamanlarda ortaya cıkar...

                                //ActionLink("") =>   <a> </a>

                                //Url.Action => "/Admin/Home/Category"

                                //Url.Action => "/Shopping/ShoppingList"

                            *@



                            <a href="@Url.Action("AddToCart", new {id=item.ID})" class="adtocart">
                                <i class="icon-shopping-cart"></i>
                            </a>
                        </div>

                        <div class="panel-body text-center">
                            <h4>
                                <a href="#" class="pro-title">
                                    @item.ProductName
                                </a>
                            </h4>
                            <p class="price">$@item.UnitPrice</p>
                        </div>
                    </section>
                </div>
            }




        </div>
    </div>
</div>


@section Sepet{
    <li>
         <a href="@Url.Action("CartPage","Shopping")"> <i class="icon-shopping-cart"> Cart</i>   </a>
    </li>
    
    
    }